# touch a.cpp
# touch b.cpp
# touch c.cpp
# touch d.cpp
# touch e.cpp
mkdir -p contest
cp template.cpp ./contest/a.cpp 
cp template.cpp ./contest/b.cpp
cp template.cpp ./contest/c.cpp
cp template.cpp ./contest/d.cpp
cp template.cpp ./contest/e.cpp
cp input.txt ./contest/input.txt
cp template.cpp ./contest/template.cpp
cp output.txt ./contest/output.txt
cp contestsession ./contest/contestsession
